### ISSUE TITLE
TLS initialization failed

### ISSUE THREAD

**Issue by mrhanhan** [3nock/OTE#5]
![image](https://user-images.githubusercontent.com/29645442/170908707-bc352d1e-ae53-4f7a-9d04-c041bfc2b242.png)

**Comment by 3nock** [comment]
Have you install the OpenSSL package that comes along with Sub3 Suite?

**Comment by illtellyoulater** [comment]
@3nock I am also getting the same error, even after installing OpenSSL. 

I'm on Windows 10, using sub3suite v0.0.4 win64.

Why is it failing?
